config/routes.rb
Rails.application.routes.draw do

  get 'warning/exists'

  get 'test/index'

  resources :discounts
  resources :quantities
  resources :orders
  resources :products
  get 'privacy/index'

  get 'terms/index'

  get 'home/test'
  get 'home/pull'
  get 'home/seed'
  get 'home/roc'
  get 'home/locello'
  get 'home/polasports'
  get 'home/unity'
  get 'home/about'
  get 'home/contact'
  get 'home/confirm'

resources :products do
  member do
    get 'hide'
    get 'add'
    get 'remove'
    get 'calc_qty_disc'
    get 'add_product_to_cart'
  end
end

  resources :accounts do
    member do
      get 'approve'
      get 'unapprove'
      get 'orderas'
      get 'destroy_user'
    end
  end
  
  resources :orders do
    member do
      get 'sendorder'
      get 'cart'
      get 'addto'
      get 'kfime'
      get 'cancel_order'
    end
  end
  
  devise_for :users, controllers: { registrations: "registrations" }
  
  get 'home/index'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_user!
  def index

  end

def roc
end
def locello
end
def polasports
end
def unity
end

def confirm
end

  def pull
    # system "runas /noprofile /user:Administrator rake db:migrate"
    # @output = `rails g migration AddSortToAccount sort`
    system "git stash"
    system "git pull origin master"
    # system "bundle exec rake db:migrate"
    # @output = `rake routes`
    # @output = `rake db:migrate`
    # system "bundle exec rake db:migrate"
    # system "rake db:migrate"
    # @output = `rake db:migrate`
      # system "rake jobs:work"
      # system "rake db:seed"
  end

  def test #this has a view, so you can check variables and stuff - be careful of breaking home controller
    system "git stash"
    # Account.destroy_all
    # User.destroy_all
    # Contact.destroy_all
   `Taskkill /IM ruby.exe /F`
   #you can use the backtick method of system commands to get the output e.g. output = `echo 'hi'` => 'hi'
  end

  def seed
    # @output = `heroku pg:push db/development.sqlite3`
    
    PopulateJob.perform_async()
    # PopulateJob.performnz_async()

    # contacts.each do |contact| # populate a model of contact email addresses - had to be done to make the data searchable
    #   if Contact.find_by(code: contact.Code)
    #     puts "contact exists skipping"
    #   else
    #     Contact.create(code: contact.Code, email: contact.EmailAddress)
    #   end
    # end

    # inactive = 0 #use this to count inactive customers
    # counter = 0 #use this counter to generate an email address for some users in the loop below
    # #create accounts and users for active customers only if they don't exist already
    # activecustomers.each do |activecustomer|
    #   @contact = Contact.find_by(code: activecustomer.Code)
    #   if @contact # if there is a contact email address for this customer code, then use it
    #     if @contact.email
    #       email = @contact.email
    #     else
    #       counter = counter + 1
    #       email = counter.to_s + "@wholesaleportal.com"
    #     end
    #   else #otherwise use the counter to generate an email address
    #     counter = counter + 1
    #     email = counter.to_s + "@wholesaleportal.com"
    #   end
    #   if Account.find_by(code: activecustomer.Code) #if there is already an account, skip it
    #     puts "account exists - skipping to next one"
    #   elsif activecustomer.InactiveCust == 0 #otherwise check if it is active
    #     newuser = User.new(email: email, password: "roccloudyportal", password_confirmation: "roccloudyportal") #create the user
    #     if newuser.save
    #       newuser.add_role :user
    #       newaccount = Account.new(code: activecustomer.Code, user: newuser) #create the account and associate with user
    #       newaccount.save
    #     else
    #       puts newuser.email #if user wasn't created - show me the culprit
    #       if User.find_by(email: newuser.email) #if is was a duplicate, let's do it again, but with the counter for the email address
    #         puts "--DUPLICATE--USING COUNTER"
    #         counter = counter + 1
    #         email = counter.to_s + newuser.email
    #         newuser = User.new(email: email, password: "roccloudyportal", password_confirmation: "roccloudyportal")
    #         newuser.save
    #         newuser.add_role :user
    #         newaccount = Account.new(code: activecustomer.Code, user: newuser)
    #         newaccount.save   
    #       end
    #     end

    #   else #if the account doesn't exist, but it's inactive, then skip creation
    #     inactive = inactive + 1
    #   end
    # end
    # #update accounts with full details
    # customers.each do |customer| #use the data from customers to fill in the blanks in Accounts
    #   account = Account.find_by(code: customer.Code)
    #   if account
    #     account.update(approved: 'approved', company: customer.Name, street: customer.Street, suburb: customer.Suburb, postcode: customer.Postcode, phone: customer.Phone, contact: customer.Contact, seller_level: customer.PriceCat, sort: customer.Sort)
    #   end
    #   print "."
    # end
  end

  

end #end of class

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class='about-brand'>
Founded in 1995, ROC Cloudy’s aim is simple; to create Australian designer collections of fashion-forward, trend setting sunglasses and accessories, that are functional, understated and affordable. Today, we focus on providing fashion forward retailers and inspired individual customers our high quality eyewear.<br>

Our testing ground is our home Sydney, Australia, which is drenched in endless sunshine.<br>

We continue to be a leading established independent sunglass company housing numerous brands with a global following of both local and international audiences. Our designs are inspired by the diverse lifestyle offered by fashion culture around the globe and we are continually working on providing the latest styles to keep up with the fast paced trends in the industry.<br>
</div>

app/views/home/confirm.html.erb
<h1>Thank you - your order has been sent</h1>
<p>
<% if (current_user.has_role? :admin) || (current_user.has_role? :rep) %>
Please select a new customer to place another order.
<%= link_to 'CHOOSE CUSTOMER....', accounts_path, class: 'btn btn-default' %>
<% else %>
We will be in contact soon to confirm and process your order.
<% end %>
</p>

app/views/home/contact.html.erb
<div class='about-brand'>
AUSTRALIA office (02) 9669 3636<br>

Email: office@roccloudy.com<br>

Sales managers<br>

NSW 0420 774 533<br>

VIC    0433 166 918<br>

QLD/WA 0400 669 777<br>

QLD/TAS/NT 0433 182 889<br>

 <hr>
New Zealand office<br>

 021 904 175<br>
 </div>

app/views/home/index.html.erb
<div id="comingsoon">
<h1>ROC CLOUDY<hr>Wholesale portal coming soon...</h1>
</div>
<div class="center">
<div class="homecontainer">
<div class='homeimg' style="background-image: url('http://res.cloudinary.com/ddmbp4xnw/image/upload/v1502067804/Roc_Sunglasses_qeerf5.jpg');">
<% if (user_signed_in?) && (current_user.account) && (current_user.account.sort) && (current_user.checksort(current_user).include? 'R') %>
	<% roc = products_path(title: 'Roc Sunglasses', group: 'roc', cat: 'C') %>
<% else %>
	<% roc = home_roc_path %>
<% end %>
<%= link_to roc, class: 'homeoverlay' do %>
<!-- <img src='http://res.cloudinary.com/roc-cloudy/image/upload/v1480980887/roc_backless_ltdncr.png'> -->
<% end %>
</div>

<div class='homeimg' style="background-image:url('http://res.cloudinary.com/ddmbp4xnw/image/upload/v1501734012/Polasports_-_Print_guuisk.jpg');">
<% if (user_signed_in?) && (current_user.account) && (current_user.account.sort) && (current_user.checksort(current_user).include? 'P') %>
	<% polasports = products_path(title: 'Polasports Sunglasses', group: 'polasports') %>
<% else %>
	<% polasports = home_polasports_path %>
<% end %>
<%= link_to polasports, class: 'homeoverlay'  do %>
<!-- <img src='http://res.cloudinary.com/roc-cloudy/image/upload/v1480980887/polasports_backless_jhozlk.png'> -->
<% end %>
</div>

<div class='homeimg' style="background-image:url('http://res.cloudinary.com/ddmbp4xnw/image/upload/v1501734012/Locello_-_Print_plobj1.jpg');">
<% if (user_signed_in?) && (current_user.account) && (current_user.account.sort) && (current_user.checksort(current_user).include? 'L') %>
	<% locello = products_path(title: 'Locello Sunglasses', group: 'locello') %>
<% else %>
	<% locello = home_locello_path %>
<% end %>
<%= link_to locello, class: 'homeoverlay'  do %>
<!-- <img src='http://res.cloudinary.com/roc-cloudy/image/upload/v1480979854/locello_backless_q6dgfz.png'> -->
<% end %>
</div>

<div class='homeimg' style="background-image:url('http://res.cloudinary.com/ddmbp4xnw/image/upload/v1501734012/Unity_Sunglasses_-_Print_n45gtw.jpg');">
<% if (user_signed_in?) && (current_user.account) && (current_user.account.sort) && (current_user.checksort(current_user).include? 'U') %>
	<% unity = products_path(title: 'Unity Sunglasses', group: 'unity', cat: ['E','D']) %>
<% else %>
	<% unity = home_unity_path %>
<% end %>
<%= link_to unity, class: 'homeoverlay'  do %>
<!-- <img src='http://res.cloudinary.com/roc-cloudy/image/upload/v1480980887/unity_backless_fzdl6h.png'> -->
<% end %>
</div>
</div>
</div>

app/views/home/locello.html.erb
<div class='about-brand'>
Locello woman balance family, work, love and taking time for herself. In her busy lifestyle she wants a sunglass for all the occasions.
She knows how to exercise her right to choice, always looking for  style and affordability, but will not compromise on quality and protection.<br>

Locello is a classic & sophisticated range of 100% UV protected and polarised women's sunglasses. <br>
All sunglasses are elegantly presented with a protective case & cleaning cloth and designed with timeless beauty to protect against harsh sun conditions.<br>
</div>

app/views/home/polasports.html.erb
<div class='about-brand'>
PProoudly Australian owned, POLASPORTS sunglasses are designed with the everday sportsperson and outdoor enthusiast in mind. Perfect for the harshest sun conditions POLASPORTS provide a fusion of sports sensibilities with fashionable frames to create an exceptional and enduring product.
</div>

app/views/home/pull.html.erb
<% if Contact.find_by(code:'running', email:'running') %>
          <b style="color:red;">RUNNING SEED</b>
          <% else %>
          <b style="color:green;">FINISHED SEED</b>
          <% end %>
          <%= link_to 'PULL', home_pull_path, class: 'btn btn-info' %><%= link_to 'SEED', home_seed_path, class: 'btn btn-info' %><%= link_to 'SUICIDE', home_test_path, class: 'btn btn-danger' %>
          <br>
          <%= link_to 'TEST', test_index_path, class: 'btn btn-success' %>
<%= @output %>pulled

app/views/home/roc.html.erb
<div class='about-brand'>
At ROC Eyewear our aim is simple; to create an Australian designer collection of fashion-forward, trend setting sunglasses and accessories. That are functional, understated and affordable. Our testing ground is our home Sydney, Australia, which is drenched in endless sunshine. <br>

ROC Eyewear continues to be a leading established independent sunglass brand with a global following of both fashion retailers and inspired individual customers. Our designs are inspired by the diverse lifestyle offered by fashion culture around the globe. <br>

To us there is beauty amongst design. <br>


</div>

app/views/home/seed.html.erb
<% if Contact.find_by(code:'running', email:'running') %>
          <b style="color:red;">RUNNING SEED</b>
          <% else %>
          <b style="color:green;">FINISHED SEED</b>
          <% end %>
          <%= link_to 'PULL', home_pull_path, class: 'btn btn-info' %><%= link_to 'SEED', home_seed_path, class: 'btn btn-info' %><%= link_to 'SUICIDE', home_test_path, class: 'btn btn-danger' %>
<h1>Seed is processing in background.</h1>
<p>You sure can continue as usual - the data will follow shortly</p>
<p>:: <%= @output %> ::</p>

app/views/home/test.html.erb
<% if Contact.find_by(code:'running', email:'running') %>
          <b style="color:red;">RUNNING SEED</b>
          <% else %>
          <b style="color:green;">FINISHED SEED</b>
          <% end %>
          <%= link_to 'PULL', home_pull_path, class: 'btn btn-info' %><%= link_to 'SEED', home_seed_path, class: 'btn btn-info' %><%= link_to 'SUICIDE', home_test_path, class: 'btn btn-danger' %>
<% @products.each do |p| %>
<%= p %><br>
<% end %>

app/views/home/unity.html.erb
<div class='about-brand'>
UNITY is an established brand that has something for everyone. A fast fashion and quality product allows UNITY to be at the forefront of our wholesale business. In addition to this, UNITY excels in providing an affordable product to ensure our customers margins are always above average. Fashion, Mens, and Womens classic collections, Polarised Designs and Childrens Selections.
</div>