config/routes.rb
Rails.application.routes.draw do

  get 'warning/exists'

  get 'test/index'

  resources :discounts
  resources :quantities
  resources :orders
  resources :products
  get 'privacy/index'

  get 'terms/index'

  get 'home/test'
  get 'home/pull'
  get 'home/seed'
  get 'home/roc'
  get 'home/locello'
  get 'home/polasports'
  get 'home/unity'
  get 'home/about'
  get 'home/contact'
  get 'home/confirm'

resources :products do
  member do
    get 'hide'
    get 'add'
    get 'remove'
    get 'calc_qty_disc'
    get 'add_product_to_cart'
  end
end

  resources :accounts do
    member do
      get 'approve'
      get 'unapprove'
      get 'orderas'
      get 'destroy_user'
    end
  end
  
  resources :orders do
    member do
      get 'sendorder'
      get 'cart'
      get 'addto'
      get 'kfime'
      get 'cancel_order'
    end
  end
  
  devise_for :users, controllers: { registrations: "registrations" }
  
  get 'home/index'

  root 'home#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :quantities,  dependent: :destroy 
  has_many :products, through: :quantities
  
  def kfi
    filename = 'W' + self.id.to_s
    path = "E:\\Attache\\Attache\\ROCNZ\\KFIDATA\\Orders\\" + filename + ".kfi"
    items = []
    myquantities = self.quantities.order(brand: :asc)
    myquantities = myquantities.joins(:product).merge(Product.order(code: :asc)) #to order by associated product's code
    myquantities.each do |q|
      product = q.product.code.to_s
      qty = q.qty.to_s
      items << '"'+product+'","'+qty+'","","","",""'
    end
    notes = self.notes.to_s
    notes_first = notes[0..60].to_s
    notes_second = notes[60..-1].to_s
    firstline = '"'+self.user.account.company.strip[0..7].to_s+'","","","","","","","'+filename+'","","'+Date.today.strftime('%d%m%Y').to_s+'","","","",""'
    lastline = '<F9><F4><DOWN><DOWN><DOWN><DOWN><ENTER>,"","","'+notes_first+'","","'+notes_second+'","","","","","","","","","","",""'
    File.open(path, "w+") do |f|
      f.puts(firstline)
      items.each do |i|
        f.puts(i)
      end
      f.puts(lastline)
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :sendorder]
  skip_before_action :authenticate_user!, only: [:kfime]
  def sendorder
     # collate duplicate products
    unique_products = @order.products.uniq
    unique_products.each do |q|
      these_quantities = @order.quantities.where(product_id: q.id)
      newqty = these_quantities.sum(:qty)
      original = these_quantities.first
      original.update(qty: newqty)
      these_quantities.all.where.not(id: original.id).destroy_all
    end
    total = 0
    @order.quantities.each do |q| # change stock levels and calc order total
      oldqty = q.product.qty
      newqty = oldqty - q.qty
      q.product.update(qty: newqty)
      total = total + (q.qty * q.price)
    end
    sent = DateTime.now
    @order.update(active: false, sent: sent, total: total) # move order to pending and give it a total
    
    @account = @order.user.account
    OrderEmailJob.perform_async(@order)

    if ((current_user.has_role? :admin) || (current_user.has_role? :rep)) && (current_user.mimic)
      current_user.mimic.destroy
    end

    redirect_to "http://203.217.18.253:3000/orders/#{@order.id}/kfime"
    # redirect_to "http://nz.roccloudy.com/home/confirm"
  end

def kfime
  Order.all.last.kfi
  redirect_to "http://nz.roccloudy.com/home/confirm"
end
# def cart #if there aren't any active orders, then create one
#   product = Product.find_by(id: params[:product])
#   order = Order.create(user: current_user, active: true)
#   qty = params[:qty]
#   ProductOrder.create(order: order, product: product, qty: qty)
#   redirect_to product, notice: 'successfully added to order'
# end

# def addto
#   product = Product.find_by(id: params[:product])
#   order = current_user.orders.where(active: true).last
#   qty = params[:qty]
#   ProductOrder.create(order: order, product: product, qty: qty)
#   redirect_to product, notice: 'successfully added to order'
# end

  # GET /orders
  # GET /orders.json
  def index
    # partial is being rendered in Account view, so moved to Account controller
    # this stuff is for the main index that only admin can see
    if user_signed_in?
      if (current_user.has_role? :admin)
        @orders = Order.all.order(sent: :desc)
        @orders = @orders.paginate(:page => params[:page], :per_page => 20)
      else
        redirect_to home_index_path
      end
    else
      redirect_to home_index_path
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @sellerlevel = @order.user.account.seller_level

    if params[:showcart] == 'show'
          if user_signed_in?
      if ((current_user.has_role? :admin) || (current_user.has_role? :rep)) && (current_user.mimic) #for sidecart
        @order = current_user.mimic.account.user.orders.where(active: true).last #for sidecart
      else #for sidecart
        @order = current_user.orders.where(active: true).last #for sidecart
      end #for sidecart
    end
        @showbuttons = 'show'
      else
        @showbuttons = 'noshow'
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    # if (current_user.has_role? :admin) || (current_user.has_role? :rep)
    #   @order.order_number = current_user.account.code + Order.all.count.to_s
    # else
    #   @order.order_number = Order.all.count.to_s
    # end
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order.quantities.last.product, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to home_index_path, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cancel_order
    Order.find(params[:id]).quantities.all.destroy_all
    redirect_to home_index_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:showcart, :total, :user_id, :notes, :cust_order_number, :order_number, :delivery_date)
    end
  end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

   

    <%= f.input :notes, as: :text %>
    <%= f.input :delivery_date, label: 'delivery date:' %>
    <%= f.input :cust_order_number, label: 'your purchase order number:' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/_index.html.erb
<h1>Orders</h1>
<% if @pendingorders.any? %>
	<ul>
	<% @pendingorders.each do |o| %>
		<%= link_to o do %>
			<li><%= o.sent.strftime("%d/%m/%y | %H:%M %p") %></li>
		<% end %>
	<% end %>
	</ul>
<% else %>
	you haven't placed any orders yet
<% end %>

<hr>
<% if @approvedorders.any? %>
<h1>Approved Orders</h1>
<% @approvedorders.each do |order| %>
<% end %>
<%= will_paginate @approved %>
<hr>
<% end %>
<% if @sentorders.any? %>
<h1>Fulfilled Orders</h1>
<% @sentorders.each do |order| %>
<% end %>
<%= will_paginate @sentorders %>
<% end %>

app/views/orders/_show.html.erb
<p id="notice"><%= notice %></p>


<% @order.quantities.each do |po| %>
<div class="po">
	<%= po.product.code %>
	<%= current_user.account.seller_level %>
	<% case current_user.account.seller_level.to_i %>
		  	<% when 1 %>
		  		$<%= po.product.price1 %>
		    <% when 2 %>
		  		$<%= po.product.price2 %>
		    <% when 3 %>
		  		$<%= po.product.price3 %>
		    <% when 4 %>
		  		$<%= po.product.price4 %>
		    <% when 5 %>
		  		$<%= po.product.price5 %>
		    <% when 6 %>
		  		$<%= po.product.rrp %>
	<% end %>
	x <%= po.qty %>
</div>
<%= link_to 'remove', remove_product_path(id: po.id), class: 'btn btn-warning remove-btn' %>
<% end %>
<hr>
<%= link_to ' SEND ORDER', send_order_path(@order), class: 'fa fa-paper-plane btn btn-info' %><hr>
<%= link_to ' cancel', order_path(@order), method: :delete, class: 'fa fa-trash btn btn-danger' %>

app/views/orders/_sidecart.html.erb
 
<% if @order %>
<% @order.total = 0 %>
  <% if @order.quantities.any? %>

  <!-- GIVE EACH NEW QUANTITY A BRAND NAME ON CREATION, THEN YOU CAN DO .order(brand...etc -->
  
  <% @order.quantities.order(brand: 'ASC').each do |po| %>
  <% if @order.quantities.where(product: po.product).count > 1 %>
  <div class="po warning">
  Item already in cart<br>
  <% else %>
  <div class="po">
  <% end %>
    <%= link_to product_path(Product.find_by(code: po.product.code)) do %>
    <div class="product-thumbnail">
    <%= cl_image_tag(po.product.code.strip + ".jpg") %>
    </div>
  <%= po.product.code %>
    <% end %>
      <% if ((current_user.has_role? :admin) || (current_user.has_role? :rep)) && (!current_user.mimic.nil?) %>
                      <% level = current_user.mimic.account.seller_level.to_i %>
                      <% thisperson = current_user.mimic.account.user %>
                    <% else %>
                      <% level = current_user.account.seller_level.to_i %>
                      <% thisperson = current_user %>
                    <% end %>
                    <% case level %>
                      <% when 1 %>
                        <% oldprice = po.product.price1 %>
                        <% prodprice = po.product.calc_discount(thisperson, po.product.price1, po.product.group, po.product.code, po.product.pricecat, po.qty) %>
                      <% when 2 %>
                        <% oldprice = po.product.price2 %>
                        <% prodprice = po.product.calc_discount(thisperson, po.product.price2, po.product.group, po.product.code, po.product.pricecat, po.qty) %>
                      <% when 3 %>
                        <% oldprice = po.product.price3 %>
                        <% prodprice = po.product.calc_discount(thisperson, po.product.price3, po.product.group, po.product.code, po.product.pricecat, po.qty) %>
                      <% when 4 %>
                        <% oldprice = po.product.price4 %>
                        <% prodprice = po.product.calc_discount(thisperson, po.product.price4, po.product.group, po.product.code, po.product.pricecat), po.qty %>
                      <% when 5 %>
                        <% oldprice = po.product.price5 %>
                        <% prodprice = po.product.calc_discount(thisperson, po.product.price5, po.product.group, po.product.code, po.product.pricecat, po.qty) %>
                      <% when 6 %>
                        <% oldprice = po.product.rrp %>
                        <% prodprice = po.product.rrp %>
                    <% end %>
                    
    $<%= number_with_precision(prodprice, precision: 2)%>
    <% subtotal = (po.qty * prodprice).round(2) %>
    <div class="qty"> x <%= po.qty %> <%= link_to '', edit_quantity_path(po), class: 'fa fa-pencil-alt' %></div> ------- $<%= number_with_precision(subtotal, precision: 2) %>
    <% @order.total = @order.total + subtotal %>

  <%= link_to 'remove', remove_product_path(id: po.id), remote:true, data: {"qty": po.qty, "price": prodprice, "disable-with": "removing..."}, class: 'btn btn-warning remove-btn', :onclick => "removeMe(this)" %></div>

  <% end %>
  <% end %>
  <hr>
  TOTAL QTY = <div id="totalqty" class="totals"><%= @order.quantities.all.sum(:qty) %></div><br>
  TOTAL (excl. freight & GST) = $<div id="totalprice" class="totals"><%= number_with_precision(@order.total, precision: 2) %></div>
  <% if (current_user.account.company.blank? || current_user.account.phone.blank?) && !((current_user.has_role? :admin) || (current_user.has_role? :rep)) %>
  <%= link_to 'please fill in your account details before placing an order', account_path(current_user.account), class: 'btn btn-info' %> <hr>
  <% else %>
  <hr>
  <% if !@order.notes.blank? %>
    Notes:  <%= @order.notes %>
    <%= link_to ' ', edit_order_path(@order), class: 'fa fa-pencil-alt btn btn-warning' %><br>
  <% else %>
    <%= link_to ' ADD NOTES', edit_order_path(@order), class: 'fa fa-pencil-alt btn btn-warning' %><br>
  <% end %>

  <% if @order.delivery_date %>
    <%= link_to @order.delivery_date, edit_order_path(@order), class: 'fa fa-calendar btn btn-warning' %><br> 
  <% else %>
    <%= link_to ' DELIVERY DATE', edit_order_path(@order), class: 'fa fa-calendar btn btn-warning' %> 
  <% end %>
  <%= link_to ' SEND ORDER', sendorder_order_path(@order, total: @order.total), class: 'fa fa-paper-plane btn btn-info', id: 'sendorder' %>
  <hr>
  <% end %>
  <%= link_to ' cancel', cancel_order_order_path(@order), class: 'fa fa-trash btn btn-danger' %>
<% end %>

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
<table class="table table-striped">
	<tr>
		<th>Date</th>
		<th>Order No.</th>
		<th>Company</th>
		<th>Status</th>
		<th></th>
	</tr>
	<% @orders.each do |order| %>	
		<tr>
			<td><%= order.sent %></td>
			<td><%= order.order_number %></td>
			<td><%= order.user.account.company %></td>
			<td><% if !order.sent %>
					<span style="color:grey">unsent</span>
				<% else %>
					<span style="color:green;">sent</span>
				<% end %></td>
			<td><%= link_to order_path(order) do %>VIEW ORDER<% end %></td>
		</tr>
		
	<% end %>
</table>
<%= will_paginate @orders %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<span id="notice"><%= notice %></span>
<a onclick="window.print();" style="cursor:pointer;">Print this page</a>

    
<style>
* {
  font-family: 'Verdana', sans-serif;
}
body, p, i, b, td{
  font-size:10px;
}
h1{
  font-size:15px;
}

</style>
<table style="width:600px; text-align:center;" align="center" width="600">
  <tbody>
    <tr style="font-family: 'Verdana', sans-serif; font-size: 10px; width:600px;" width="600">
      <td>
<table style="width:600px; text-align:center;" align="center" width="600">
  <tbody>
    <tr align="left" style="text-align:left; font-size:10px; font-family: 'Verdana', sans-serif;">
      <td style="font-size:10px; font-family: 'Verdana', sans-serif; width:150px;" width="150"><b>Customer</b></td><td><%= @order.user.account.company %></td>
    </tr>
    <tr align="left" style="text-align:left; font-size:10px; font-family: 'Verdana', sans-serif;">
      <td style="font-size:10px; font-family: 'Verdana', sans-serif; width:150px;" width="150"><b>Cust No.</b></td><td><%= @order.user.account.code %></td>
    </tr>
    <tr align="left" style="text-align:left; font-size:10px; font-family: 'Verdana', sans-serif;">
      <td style="font-size:10px; font-family: 'Verdana', sans-serif; width:150px;" width="150"><b>Address</b></td><td><%= @order.user.account.street %>
        <%= @order.user.account.suburb %> <%= @order.user.account.postcode %></td>
      </tr>
      <tr align="left" style="text-align:left;">
        <td style="font-size:10px; font-family: 'Verdana', sans-serif; width:150px;" width="150">
          Notes:
        </td>
        <td style="font-size:10px; font-family: 'Verdana', sans-serif;">
          <%= @order.notes %>
        </td>
      </tr>
      <tr align="left" style="text-align:left;">
        <td style="font-size:10px; font-family: 'Verdana', sans-serif; width:150px;" width="150">
          Order number:
        </td>
        <td style="font-size:10px; font-family: 'Verdana', sans-serif;">
          <%= @order.order_number %>
        </td>
      </tr>
      <tr align="left" style="text-align:left;">
        <td style="font-size:10px; font-family: 'Verdana', sans-serif; width:150px;" width="150">
          Customer order number:
        </td>
        <td style="font-size:10px; font-family: 'Verdana', sans-serif;">
          <%= @order.cust_order_number %>
        </td>
      </tr>
      <tr align="left" style="text-align:left;">
        <td style="font-size:10px; font-family: 'Verdana', sans-serif; width:150px;" width="150">
          Delivery date:
        </td>
        <td style="font-size:10px; font-family: 'Verdana', sans-serif;">
          <%= @order.delivery_date %>
        </td>
      </tr>
    </tbody>
  </table>
</td>
</tr>
<tr style="font-family: 'Verdana', sans-serif; font-size: 10px; width:600px;" width="600">
  <td>
  <table style="width:600px; text-align:center;" align="center" width="600">
    <tbody>
      <tr style="font-family: 'Verdana', sans-serif; font-size: 10px; width:600px;" width="600">
        <th style="font-size:10px; font-family: 'Verdana', sans-serif; width:40px;" width="40">Item No.</th>
        <th style="font-size:10px; font-family: 'Verdana', sans-serif; width:30px;" width="30">Qty</th>
        <th style="font-size:10px; font-family: 'Verdana', sans-serif; width:380px;" width="380">Description</th>
        <th style="font-size:10px; font-family: 'Verdana', sans-serif; width:50px; text-align:right;" width="50" align="right">Price</th>
        <th style="font-size:10px; font-family: 'Verdana', sans-serif; width:50px; text-align:right;" width="50" align="right">Subtotal</th>
      </tr>
      <% @order.quantities.order(brand: 'ASC').each do |q| %>
      <% case @order.user.account.seller_level.to_i %>
      <% when 1 %>
      <% oldprice = q.product.price1 %>
      <% when 2 %>
      <% oldprice = q.product.price2 %>
      <% when 3 %>
      <% oldprice = q.product.price3 %>
      <% when 4 %>
      <% oldprice = q.product.price4 %>
      <% when 5 %>
      <% oldprice = q.product.price5 %>
      <% when 6 %>
      <% oldprice = q.product.rrp %>
      <% end %>
      <% case @order.user.account.seller_level.to_i %>
      <% when 1 %>
      <% prodprice = q.product.calc_discount(@order.user, q.product.price1, q.product.group, q.product.code, q.product.pricecat, q.qty) %>
      <% when 2 %>
      <% prodprice = q.product.calc_discount(@order.user, q.product.price2, q.product.group, q.product.code, q.product.pricecat, q.qty) %>
      <% when 3 %>
      <% prodprice = q.product.calc_discount(@order.user, q.product.price3, q.product.group, q.product.code, q.product.pricecat, q.qty) %>
      <% when 4 %>
      <% prodprice = q.product.calc_discount(@order.user, q.product.price4, q.product.group, q.product.code, q.product.pricecat), q.qty %>
      <% when 5 %>
      <% prodprice = q.product.calc_discount(@order.user, q.product.price5, q.product.group, q.product.code, q.product.pricecat, q.qty) %>
      <% when 6 %>
      <% prodprice = q.product.rrp %>
      <% end %>

      <% subtotal = (q.qty * prodprice) %>
      <tr>
        <td align="left" style="text-align:left; font-size:10px; font-family: 'Verdana', sans-serif; width:40px;" width="40"><%= q.product.code %></td>
        <td style="font-size:10px; font-family: 'Verdana', sans-serif; width:30px;" width="30"><%= q.qty %></td>
        <td style="text-align:left;font-size:10px; font-family: 'Verdana', sans-serif; width:390px;" width="390"><%= q.product.description %></td>
        <td style="text-align:right; font-size:10px; font-family: 'Verdana', sans-serif; width:40px;" width="40" align="right">$<%= number_with_precision(prodprice, precision: 2)%></td>
        <td style="font-size: 10px; width:50px; text-align:right; font-family: 'Verdana', sans-serif;" width="50" align="right">$<%= number_with_precision(subtotal, precision: 2) %></td>
      </tr>
      <% end %>
      <tr align="left" style="text-align:left;">
          <td></td><td></td><td></td>
          <td style="text-align:right;" align="right">
            <b style="font-size:12px; font-family: 'Verdana', sans-serif;">QTY :</b>
          </td>
          <td style="text-align:right;" align="right">
            <b style="font-size:12px; font-family: 'Verdana', sans-serif;"><%= @order.quantities.all.sum(:qty) %></b>
          </td>
        </tr>
      <% if @order.total %>
      <tr align="left" style="text-align:left;">
        <td></td><td></td><td></td>
        <td style="text-align:right;" align="right">
          <b style="font-size:12px; font-family: 'Verdana', sans-serif;">SUBTOTAL :</b>
        </td>
        <td style="text-align:right;" align="right">
          <b style="font-size:12px; font-family: 'Verdana', sans-serif;">
            $<%= (@order.total).round(2) %>
          </b>
        </td>
      </tr>
      <tr align="left" style="text-align:left;">
        <td></td><td></td><td></td>
        <td style="text-align:right;" align="right">
          <b style="font-size:12px; font-family: 'Verdana', sans-serif;">GST :</b>
        </td>
        <td style="text-align:right;" align="right">
          <b style="font-size:12px; font-family: 'Verdana', sans-serif;">$<%= (@order.total * 0.1).round(2) %></b>
        </td>
      </tr>

      <tr align="left" style="text-align:left;">
        <td></td><td></td><td></td>
        <td style="text-align:right;" align="right">
          <b style="font-size:12px; font-family: 'Verdana', sans-serif;">TOTAL :</b>
        </td>
        <td style="text-align:right;" align="right">
          <b style="font-size:12px; font-family: 'Verdana', sans-serif;">$<%= (@order.total + (@order.total * 0.1).round(2)) %></b>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</td>
</tr>
</tbody>
</table>

<% if @showbuttons == 'show' %>
<div class="col-md-3 cart" id="cart" style="width:100%; display:block; left:0; border-radius:0;">
        <p>
          <i class="fa fa-shopping-cart fa-2x"></i>
        </p>
        <hr>
        <p>
          <%= render 'orders/sidecart' %>
        </p>
      </div>
      <% end %>