config/routes.rb
Rails.application.routes.draw do

  get 'warning/exists'

  get 'test/index'

  resources :discounts
  resources :quantities
  resources :orders
  resources :products
  get 'privacy/index'

  get 'terms/index'

  get 'home/test'
  get 'home/pull'
  get 'home/seed'
  get 'home/roc'
  get 'home/locello'
  get 'home/polasports'
  get 'home/unity'
  get 'home/about'
  get 'home/contact'
  get 'home/confirm'

resources :products do
  member do
    get 'hide'
    get 'add'
    get 'remove'
    get 'calc_qty_disc'
    get 'add_product_to_cart'
  end
end

  resources :accounts do
    member do
      get 'approve'
      get 'unapprove'
      get 'orderas'
      get 'destroy_user'
    end
  end
  
  resources :orders do
    member do
      get 'sendorder'
      get 'cart'
      get 'addto'
      get 'kfime'
      get 'cancel_order'
    end
  end
  
  devise_for :users, controllers: { registrations: "registrations" }
  
  get 'home/index'

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	# validates :company, :phone, :state, :suburb, :street, :presence => true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/discount.rb
class Discount < ActiveRecord::Base
end

app/models/mimic.rb
class Mimic < ActiveRecord::Base
  belongs_to :account
  belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :quantities,  dependent: :destroy 
  has_many :products, through: :quantities
  
  def kfi
    filename = 'W' + self.id.to_s
    path = "E:\\Attache\\Attache\\ROCNZ\\KFIDATA\\Orders\\" + filename + ".kfi"
    items = []
    myquantities = self.quantities.order(brand: :asc)
    myquantities = myquantities.joins(:product).merge(Product.order(code: :asc)) #to order by associated product's code
    myquantities.each do |q|
      product = q.product.code.to_s
      qty = q.qty.to_s
      items << '"'+product+'","'+qty+'","","","",""'
    end
    notes = self.notes.to_s
    notes_first = notes[0..60].to_s
    notes_second = notes[60..-1].to_s
    firstline = '"'+self.user.account.company.strip[0..7].to_s+'","","","","","","","'+filename+'","","'+Date.today.strftime('%d%m%Y').to_s+'","","","",""'
    lastline = '<F9><F4><DOWN><DOWN><DOWN><DOWN><ENTER>,"","","'+notes_first+'","","'+notes_second+'","","","","","","","","","","",""'
    File.open(path, "w+") do |f|
      f.puts(firstline)
      items.each do |i|
        f.puts(i)
      end
      f.puts(lastline)
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
has_many :quantities,  dependent: :destroy 
has_many :orders, through: :quantities

def self.all_cached
  Rails.cache.fetch('Product.all') { all.to_a }
end

def calc_discount(u, price, prod_group, prod_code, price_cat, qty)
	
	# if discos = Discount.all.where(product: (prod_group || prod_code || price_cat), customer: (u.account.code || u.account.discount))
		# FOR SOME REASON CHANGING THE ORDER OF THE 'price_cat || prod_code || prod_group' WORKS? THIS COULD MEAN SOMETHING ELSE IS WRONG
		# discos = (Discount.all.where(product: price_cat , customer: u.account.code)) || (Discount.all.where(product: prod_code , customer: u.account.code)) || (Discount.all.where(product: prod_group , customer: u.account.code)) || (Discount.all.where(product: price_cat , customer: u.account.discount)) || (Discount.all.where(product: prod_code , customer: u.account.discount)) || (Discount.all.where(product: prod_group , customer: u.account.discount))
	if discos = Discount.all.where('(product = ? AND (producttype = ? OR producttype = ?)) OR (product = ? AND (producttype = ? OR producttype = ?)) OR (product = ? AND (producttype = ? OR producttype = ?))', price_cat, 'cat_fixed', 'cat_percent' , prod_code , 'code_fixed', 'code_percent', prod_group, 'group_fixed', 'group_percent').where('customer = ? OR customer = ?', u.account.code, u.account.discount)

		if disco = discos.all.where('maxqty >= ?', qty).first
		    if disco.disctype == 'fixedtype'
		      result =  disco.discount
		    else
		      result = price - ((price / 100) * disco.discount)
		    end
		else
			result = price
		end
	else
		result = price
	end

	return result.to_d.round(2)
end




end #end of class

app/models/product_order.rb
class ProductOrder < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  validates :qty, numericality: { greater_than_or_equal_to: 1 }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true
             # :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_one :account,  dependent: :destroy 
  has_one :mimic,  dependent: :destroy 
  has_many :orders,  dependent: :destroy 
  
  after_create :assign_default_role

   # after_update :send_change_email

  def assign_default_role
      add_role(:user)
  end

  # def send_change_email
    # AdminMailer.account_change_request('office@roccloudy.com', User.all.find_by(id: id).account).deliver_now
  # end

  def checksort(user)
    if (user.has_role? :admin) || (user.has_role? :rep)
      if user.mimic
        output = user.mimic.account.sort
      else
        output = 'R L U P'
      end
    else
      output = user.account.sort
    end
    if output == nil
      output = ' '
    end
    return output
  end 

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/warning_helper.rb
module WarningHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roc Cloudy | Wholesale</title>
  <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Lobster|Scope+One|Vesper+Libre" rel="stylesheet">
  
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to home_index_path , class:'navbar-brand' do %>
          <img src="http://res.cloudinary.com/roc-cloudy/image/upload/v1479963402/RocCloudy_axxjva.jpg">
        <% end %>
        <% if user_signed_in? && current_user.orders.any? && current_user.orders.last.active == true %>
            <%= link_to 'View Cart', order_path(current_user.orders.where(active: true).last, showcart: 'show'), class: 'mobile-cart-btn' %>
            <% end %> 

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if @notice != nil %>
        <%= @notice %>
        <% end %>
        <% if user_signed_in? %>

        <% if ((current_user.has_role? :admin) || (current_user.has_role? :rep)) && (current_user.mimic) %>
        <div id="mimic">
          <% if !current_user.mimic.account.nil? %>
            ORDERING FOR: 
            <%= current_user.mimic.account.company %>
            <% account = current_user.account %>
            <% if current_user.mimic.account.dispute %>
            <b>Credit on hold</b>
            <% end %>
            <%= link_to orderas_account_path(account, account: 'clear'), class: 'btn btn-danger' do %>
              <i class="fa fa-close" style="color:#FFF; vertical-align: middle;"></i>
            <% end %>
          <% end %>
        </div>
        <% end %>

        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <% if current_user.account %>
              <% if current_user.account.sort %>
                <% sortfield = current_user.checksort(current_user) %>
                <% if sortfield.include? 'R' %>
                  <li class="dropdown menu-icon">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="http://res.cloudinary.com/roc-cloudy/image/upload/v1480980887/roc_backless_ltdncr.png"></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Sunglasses', products_path(title: 'Roc Sunglasses', group: 'roc', cat: 'C') %></li>
                      <li><%= link_to 'Hats', products_path(title: 'Roc Hats', group: 'roc', cat: 'J') %></li>
                      <li><%= link_to 'New arrivals', products_path(title: 'Roc New Arrivals', group: 'roc', filter: 'new') %></li>
                    </ul>
                  </li>
                <% end %>
                <% if sortfield.include? 'P' %>
                  <li class="dropdown-menu-icon"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <img src="http://res.cloudinary.com/roc-cloudy/image/upload/v1480980887/polasports_backless_jhozlk.png">
                  </a><ul class="dropdown-menu"><li><%= link_to 'All Sunglasses', products_path(title: 'Polasports Sunglasses', group: 'polasports') %></li>
                  <li><%= link_to 'New arrivals', products_path(title: 'Polasports New Arrivals', group: 'polasports', filter: 'new') %></li></ul></li>
                  </li>
                <% end %>
                <% if sortfield.include? 'L' %>
                  <li class="dropdown-menu-icon"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="http://res.cloudinary.com/roc-cloudy/image/upload/v1480979854/locello_backless_q6dgfz.png"></a><ul class="dropdown-menu"><li><%= link_to 'All Sunglasses', products_path(title: 'Locello Sunglasses', group: 'locello') %></li>
                  <li><%= link_to 'New arrivals', products_path(title: 'Locello New Arrivals', group: 'locello', filter: 'new') %></li></ul></li>
                <% end %>
                <% if sortfield.include? 'U' %>
                  <li class="dropdown menu-icon"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="http://res.cloudinary.com/roc-cloudy/image/upload/v1480980887/unity_backless_fzdl6h.png"></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'All Sunglasses', products_path(title: 'Unity Sunglasses', group: 'unity', cat: ['E','D']) %></li>
                      <li><%= link_to 'Fashion', products_path(title: 'Unity Fashion', group: 'unity', cat: 'E', filter: 'FASHION') %></li>
                      <li><%= link_to 'Mens', products_path(title: 'Unity Mens', group: 'unity', cat: 'E', filter: 'MENS') %></li>
                      <li><%= link_to 'Mens Polarised', products_path(title: 'Unity Mens Polarised', group: 'unity', cat: 'E', filter: 'MENS POLARISED') %></li>
                      <li><%= link_to 'Womens', products_path(title: 'Unity Womens', group: 'unity', cat: 'E', filter: 'WOMENS') %></li>
                      <li><%= link_to 'Womens Polarised', products_path(title: 'Unity Womens Polarised' , group: 'unity', cat: 'E', filter: 'WOMENS POLARISED') %></li>
                      <li><%= link_to 'Kids', products_path(title: 'Unity Kids', group: 'unity', cat: 'D') %></li>
                      <li><%= link_to 'Reading', products_path(title: 'Unity Reading', group: 'unity', cat: ['R','Z']) %></li>
                      <li><%= link_to 'Accessories', products_path(title: 'Unity Accessories', group: 'unity', cat: 'A') %></li>
                      <li><%= link_to 'New arrivals', products_path(title: 'Unity New Arrivals', group: 'unity', filter: 'new') %></li>
                    </ul>
                  </li>
                <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <% if (current_user.has_role? :admin) || (current_user.has_role? :rep) %>
            <li><%= link_to 'Customers', accounts_path %></li>
            <% else %>
            <% if current_user.approved? %>
            <li><%= link_to 'My Account', new_user_session_path %></li>
            <% else %>
            <% if !current_user.account %>
            <li><%= link_to 'create account for approval', new_account_path(current_user) %></li>
            <% else %>
            <% if current_user.account.approved != 'approved' %>
            <li><%= link_to 'your account is pending approval', account_path(current_user.account) %></a></li>
            <% else %>
            <li><%= link_to 'my account', account_path(current_user.account) %></a></li>
            <% end %>
            <% end %>
            <% end %>

            <% end %>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            <% if current_user.orders.any? && current_user.orders.last.active == true %>
            <li><%= link_to 'View Cart', order_path(current_user.orders.where(active: true).last, showcart: 'show') %></li>
            <% end %> 


            <% else %>
            
            <li class="dropdown menu-icon"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
              <ul class="dropdown-menu" style="text-align:center;">
                <li><%= link_to 'Roc', home_roc_path %></li>
                <li><%= link_to 'Polasports', home_polasports_path %></li>
                <li><%= link_to 'Locello', home_locello_path %></li>
                <li><%= link_to 'Unity', home_unity_path %></li>
              </ul>
            </li>
            <li><%= link_to 'About us', home_about_path %></li>
            <li><%= link_to 'Contact us', home_contact_path %></li>          
            <li><%= link_to 'Log in', new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="mycontainer">
      <%= yield %>
    </div>

    <div class="footer">
      <%= link_to 'terms', terms_index_path %> | <%= link_to 'privacy', privacy_index_path %>
      <% if !user_signed_in? %>
      | <%= link_to 'sign up', new_user_registration_path %> | <%= link_to 'log in', new_user_session_path %>
      <% end %>
      | copyright &copy; <%= Time.now.year %> Roc Cloudy Pty Ltd
    </div>

  </body>
  </html>