config/routes.rb
Rails.application.routes.draw do

  get 'warning/exists'

  get 'test/index'

  resources :discounts
  resources :quantities
  resources :orders
  resources :products
  get 'privacy/index'

  get 'terms/index'

  get 'home/test'
  get 'home/pull'
  get 'home/seed'
  get 'home/roc'
  get 'home/locello'
  get 'home/polasports'
  get 'home/unity'
  get 'home/about'
  get 'home/contact'
  get 'home/confirm'

resources :products do
  member do
    get 'hide'
    get 'add'
    get 'remove'
    get 'calc_qty_disc'
    get 'add_product_to_cart'
  end
end

  resources :accounts do
    member do
      get 'approve'
      get 'unapprove'
      get 'orderas'
      get 'destroy_user'
    end
  end
  
  resources :orders do
    member do
      get 'sendorder'
      get 'cart'
      get 'addto'
      get 'kfime'
      get 'cancel_order'
    end
  end
  
  devise_for :users, controllers: { registrations: "registrations" }
  
  get 'home/index'

  root 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	# validates :company, :phone, :state, :suburb, :street, :presence => true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :approve, :unapprove]
  before_action :securitycheck, only: [:index, :approve, :unapprove, :destroy]

  def destroy_user
    @user = User.find(params[:user])
    @user.destroy
    redirect_to accounts_path
  end

#   check if user is admin - if not send them back home --- set which actions up top in the before_action
  def securitycheck
    if !((current_user.has_role? :admin) || (current_user.has_role? :rep))
      redirect_to home_index_path
    end
  end

def orderas
  if params[:account] == 'clear'
    current_user.mimic.destroy #if they choose to order as themselves, just wipe it clean
  else
    account = Account.find_by(id: params[:account])
    if current_user.mimic
      current_user.mimic.update(account: account) #if they are already mimicing, then just update
    else
      Mimic.create(account: account, user: current_user) #if they are fresh to a mimic, then creat the record
    end
  end
  redirect_to home_index_path
end

def approve
  @account.update_attributes(:approved => 'approved')
  UserMailer.approved_email(@account.user.email).deliver_now
  redirect_to accounts_path, notice: 'Account approved'
end
def unapprove
  @account.update_attributes(:approved => 'unapproved')
  redirect_to accounts_path, notice: 'Account unapproved'
end

  # GET /accounts
  # GET /accounts.json
  def index    
    if params[:searchterm]
      searchterm = params[:searchterm]
      @accounts = Account.where('lower(company) LIKE ? OR lower(code) LIKE ?', "%#{searchterm.downcase}%", "%#{searchterm.downcase}%")
    else
      @accounts = Account.all.order(approved: :asc, created_at: :desc)
    end
    if params[:order]
      @accounts = @accounts.order(params[:order] + ' ASC')
    end
    if params[:search]
      @accounts = @accounts.where(code: params[:search])
    end
    case current_user.account.code
      when 'REPNSW'
        @accounts = @accounts.where('rep LIKE ? OR rep LIKE ?', '%GT%', '%GTS%')
      when 'REPVIC'
        @accounts = @accounts.where('rep LIKE ?', '%CC%')
      when 'REPQLD1'
        @accounts = @accounts.where('rep LIKE ? OR rep LIKE ?', '%SG%', '%SGW%')
      when 'REPQLD2'
        @accounts = @accounts.where('rep LIKE ? OR rep LIKE ? OR rep LIKE ?', '%SK%', '%SKT%', '%SKN%')
    end
    # if current_user.email != 'web@roccloudy.com'
    #   @accounts = @accounts.where(rep: current_user.account.code)
    # end
    @accounts = @accounts.paginate(:page => params[:page], :per_page => 20)

    @blank_accounts = User.all.where(approved: false)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    if (current_user.has_role? :admin) || (current_user.has_role? :rep)
      account = Account.find(params[:id])

      @pendingorders = Order.where(user: account.user, active: false, approved: false, complete: false)
      @approvedorders = Order.where(user:account.user, active:false, approved: true, complete: false)
      @sentorders = Order.where(user:account.user, active:false, approved: true, complete: true)
    else
      @pendingorders = Order.where(user: current_user, active: false, approved: false, complete: false)
      @approvedorders = Order.where(user:current_user, active:false, approved: true, complete: false)
      @sentorders = Order.where(user:current_user, active:false, approved: true, complete: true)
    end
    @pendingorders = @pendingorders.order(created_at: :desc).limit(5)
    @approvedorders = @approvedorders.order(created_at: :desc).limit(5)
    @sentorders = @sentorders.order(created_at: :desc).limit(5)
    # @sentorders = @sentorders.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user = current_user
    @account.code = @account.company.upcase[0..5]
    @account.sort = @account.sort.upcase
    i = 1
    until !Account.find_by(code: @account.code)
      newcode = @account.code + i.to_s
      if !Account.find_by(code: newcode)
        @account.code = newcode
      else
        i += 1
      end
    end 
    if Account.where("code LIKE CONCAT('%',?,'%')", @account.company.upcase[0..5]).count >= 2
        @alert = Account.where("code LIKE CONCAT('%',?,'%')", @account.code).first
        current_user.update(approved: false)
        redirect_to warning_exists_path
    else
      respond_to do |format|
        if @account.save
          EmailJob.perform_async('cheryl@roccloudy.com', @account) #email admin with notification
          UserEmailJob.perform_async(@account.user.email) #email the user with a receipt

          format.html { redirect_to @account, notice: 'Account was successfully created.' }
          format.json { render :show, status: :created, location: @account }
        else
          format.html { render :new }
          format.json { render json: @account.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        @account.update(sort: @account.sort.upcase)
        AdminMailer.account_change_request('office@roccloudy.com', @account).deliver_now
        format.html { redirect_to accounts_path, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:brands, :user_id, :website, :rep, :code, :company, :street, :suburb, :postcode, :state, :country, :phone, :contact, :seller_level, :sort, :discount)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
      <% if current_user.has_role? :admin %>
        <%= f.input :code %>
        <% else %>
        <%= link_to "Change login credentials", edit_user_registration_path, class: 'btn btn-warning' %>
      <% end %>
    <%= f.input :company %>
    <%= f.input :street %>
    <%= f.input :suburb %>
    <%= f.input :postcode %>
    <%= f.input :state %>
    <%= f.input :country %>
    <%= f.input :phone %>
    <%= f.input :brands, label: 'Which brands/items are you interested in?'%>
    <%= f.input :contact, label: 'contact name' %>
    <%= f.input :website %>

    <% if current_user.has_role? :admin %>
    <% if !@account.seller_level || @account.seller_level == '' %>
    <div class="highlight-field">
    <%= f.input :seller_level %>
    </div>
    <% else %>
    <%= f.input :seller_level %>
    <% end %>
    <%= f.input :sort %>
    <br>(**NB: changes made to sort will NOT be reflected in Attache automatically)
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'back', @account %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

Search: <input id="searchfield" type="text"><span class="btn btn-info" onclick="searchme();"><i class="fa fa-search"></i></span><br>

<table class="table table-striped">
  <thead>
    <tr>
      <th>code</th>
      <th>company</th>
      <th>phone</th>
      <th>contact</th>
      <th>email</th>
      <th>View acct.</th>
      <th></th>
      <th>Order</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
    <% if account.approved != 'approved' %>
    <tr style="background:yellow;">
      <% else %>
      <tr>
        <% end %>
        <td><%= account.code %></td>
        <td><%= account.company %></td>
        <td><%= account.phone %></td>
        <td><%= account.contact %></td>
        <% if account.user %>
        <td><%= account.user.email %></td>
        <% else %>
        <td>no user assoc.</td>
        <% end %>
        <td>
          <% if account.dispute %>
          <b>Credit on hold</b><br>
        <% end %>
          <%= link_to account_path(account) do %>
            <i class='fa fa-eye'></i>
          <% end %>
        </td>
        <% if account.approved == 'approved' %>
        <% if !account.seller_level? %>
        <td>
          <%= link_to edit_account_path(account), class: 'btn btn-warning', title: 'seller level required' do %>
            <i class="fa fa-exclamation-triangle"></i>
          <% end %>
          Approved 
          <% if (current_user.has_role? :admin) || (current_user.has_role? :rep) %>
            <%= link_to unapprove_account_path(account), class: 'btn btn-danger' do %>
              <i class="fa fa-thumbs-o-down">
            </i> Unapprove
            <% end %>
          <% end %>
        </td>
        <% else %>
        <td>Approved
          <% if (current_user.has_role? :admin) || (current_user.has_role? :rep) %>
            <%= link_to unapprove_account_path(account), class: 'btn btn-danger' do %>
            <i class="fa fa-thumbs-o-down"></i> Unapprove
            <% end %>
          <% end %>
        </td>
        <% end %>
        <% else %>
        <td>Not approved
        <% if (current_user.has_role? :admin) || (current_user.has_role? :rep) %>
          <%= link_to approve_account_path(account), class: 'btn btn-info' do %>
            <i class="fa fa-thumbs-o-up"></i> Approve
          <% end %>
        <% end %>
        </td>
        <% end %>
        <td>
          <%= link_to orderas_account_path(account, account: account), class: 'btn btn-info' do %>
          <i class="fa fa-shopping-cart"></i>
          <% end %>
        </td>
      </tr>
      
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @accounts %>


  <hr>
  <p><b>Users with no account</b></p>
  <% @blank_accounts.each do |u| %>
    <%= u.email %><%= link_to 'delete user', destroy_user_account_path(id: 1, user: u.id), class: 'btn btn-danger' %><br>
  <% end %>

app/views/accounts/new.html.erb
<h1>Please enter your details</h1>

<%= render 'form' %>

<p>
	Your details will be sent to your Roc Cloudy sales representative for approval.
</p>

app/views/accounts/show.html.erb
<div class="row">
<div class="col-md-6">
<p>
<strong>code:</strong>
<%= @account.code %>
</p>
<p>
  <strong>name:</strong>
  <%= @account.company %>
</p>

<p>
  <strong>street:</strong>
  <%= @account.street %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @account.suburb %>
</p>

<p>
  <strong>State:</strong>
  <%= @account.state %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @account.phone %>
</p>

<% if !@account.approved? %>
<p>
  <strong>Interested in:</strong>
  <%= @account.brands %>
</p>
<% end %>

<p>
  <strong>Contact name:</strong>
  <%= @account.contact %>
</p>

<p>
  <strong>Website:</strong>
  <%= @account.website %>
</p>



<% if !@account.approved? %>
<p>
Account is pending approval.
</p>
<% end %>
<% if current_user.has_role? :admin %>
  
<p>
  <strong>Seller level:</strong>
  <% if @account.seller_level  && @account.seller_level != '' %>
    <%= @account.seller_level %>
  <% else %>
    <%= link_to 'Please moderate', edit_account_path(@account), class: 'btn btn-warning' %>
  <% end %>
</p>
<% end %>
<% if (current_user.account) || (current_user.has_role? :admin) %>
<%= link_to 'Edit account details', edit_account_path(@account), class: 'btn btn-default' %>
  <% if current_user.has_role? :admin %>
    <%= link_to 'Order for this customer', orderas_account_path(account: @account.id), class: 'btn btn-info' %>
  <% end %>
<% end %>
</div>
<div class="col-md-6">
<%= render 'orders/index' %>
</div>
</div>